<a href="https://colab.research.google.com/github/shlok-py/Pytorch_Tutorial/blob/main/Pytorch_lesson_2_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lesson - 2: Tensors

### Importing torch library

In [ ]:
import torch
import numpy as np

### Tensors
Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data (see Bridge with NumPy). Tensors are also optimized for automatic differentiation (we’ll see more about that later in the Autograd section). If you’re familiar with ndarrays, you’ll be right at home with the Tensor API. If not, follow along!

**Copied from** https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html


---

## Initializing Tensors
Method 1: **Directly from data**

In [ ]:
data = [[1, 2],[3, 4]]
print("Data: ",data, end = "\n")
x_data = torch.tensor(data)
print("Converted into Tensor", x_data)

Data:  [[1, 2], [3, 4]]
Converted into Tensor tensor([[1, 2],
        [3, 4]])


Method 2: **From a NumPy array**

In [ ]:
nd_array = np.array([[1,2], [3,4]])
print("The numPy array:", nd_array, end = "\n")
x_np = torch.from_numpy(nd_array)
print("Converted into Tensor: ", x_np)

The numPy array: [[1 2]
 [3 4]]
Converted into Tensor:  tensor([[1, 2],
        [3, 4]])


Method 3: **From another tensor**

In [ ]:
x_ones = torch.ones_like(x_data)
print("Ones Tensor: ", x_ones, end = "\n")
x_rand = torch.rand_like(x_data, dtype = torch.float)
print("Random tensor: ", x_rand)

Ones Tensor:  tensor([[1, 1],
        [1, 1]])
Random tensor:  tensor([[0.8728, 0.8023],
        [0.5611, 0.4933]])


Method 4: **From random or constant values**

In [ ]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: {rand_tensor}")
print(f"Ones Tensor: {ones_tensor}")
print(f"Zeros Tensor: {zeros_tensor}")

Random Tensor: tensor([[0.7641, 0.3265, 0.2004],
        [0.4471, 0.3104, 0.2611]])
Ones Tensor: tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor: tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Attributes of a tensor

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device where tensor is stored in: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device where tensor is stored in: cpu


### Operations on Tensor

Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling and more are comprehensively described here.

Each of these operations can be run on the GPU (at typically higher speeds than on a CPU). If you’re using Colab, allocate a GPU by going to Runtime > Change runtime type > GPU.

By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using .to method (after checking for GPU availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

**Copied from** : https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

In [ ]:
#move tensor to GPU is available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

#### ** Standard numpy-like indexing and slicing**

In [ ]:
tensor = torch.ones(4,4)
print(f"first row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last Column: {tensor[..., -1]}")
print(tensor)
tensor[:,1] = 0
print(tensor)

first row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last Column: tensor([1., 1., 1., 1.])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Joining tensors:** You can use **torch.cat** to concatenate a sequence of tensors along a given dimension. See also **torch.stack**, another tensor joining option that is subtly different from **torch.cat**.

In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
# dimenson has the range between [-2,1]
t2 = torch.cat([tensor,tensor,tensor], dim = -2)
'''
dim = 1, concates tensor in the row
dim = 0, concates tensor in the column
'''
print(t2)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Arithmetic Operations**

In [ ]:
# @ tensor.T returns transpose of the tensor
# The following code does matrix multiplication
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(y1)
print(y2)

y3 = torch.rand_like(y1)
print(y3)
torch.matmul(tensor, tensor.T, out = y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[0.9347, 0.6240, 0.5204, 0.1465],
        [0.0305, 0.9809, 0.7714, 0.4695],
        [0.7061, 0.8172, 0.4701, 0.8599],
        [0.2095, 0.2382, 0.4549, 0.5219]])


tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [ ]:
#Elementwise product
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

#### Single-element tensors If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item():

In [ ]:
agg = tensor.sum()
agg = agg.item()
print(agg ,type(agg))

12.0 <class 'float'>


#### In-place operations Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.

In [ ]:
print(f"{tensor}")
tensor = tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


### Bridge with NumPy
Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

#### Tensor to NumPy Array

In [ ]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(type(n))

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>


#### A change in tensor reflect in NumPy array

In [ ]:
t.add_(1)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


#### NumPy to Tensor

In [ ]:
n = np.ones(5)
print(n)
t = torch.from_numpy(n)
print(t)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


#### Changes in numpy array reflects in the tensor

In [ ]:
np.add(n,1, out = n)
print(n)
print(t)

[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
